spring:
  database:
    driveClassName = org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database: POSTGRESQL
  datasource:
    platform:
    show-sql: true
    testWhileIdLe: true
example:
  property: "I AM THE DEFAULT"

management:
  endpoints:
    endpoints:
      enabled-by-default: true
    web:
      exposure:
        include: *
