spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_URL:localhost}:5432/postgres
    username: postgres
    password: postgres

eureka:
  service-url:
    default-zone: http://eureka.hostname:8761/eureka/
